# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simple_lm <- function(X, y) {
    .Call('_homework3_simple_lm', PACKAGE = 'homework3', X, y)
}

