name: R-CMD-check.yaml

on:
  push:
    branches: [main, master]
  pull_request:

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,  r: 'devel'}
          - {os: ubuntu-latest,  r: 'release'}
          - {os: ubuntu-latest,  r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Pandoc (needed for vignettes)
      - uses: r-lib/actions/setup-pandoc@v2

      # Step 3: Install R
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      # Step 4: Debug and Install qpdf on macOS
      - name: Debug and Install qpdf (macOS only)
        if: runner.os == 'macOS'
        run: |
          # Debug Homebrew
          brew update-reset || true
          brew doctor || true
          brew cleanup || true
          # Attempt to install qpdf
          brew install qpdf || echo "qpdf installation failed. Skipping..."
          # Verify installation
          if ! command -v qpdf &> /dev/null; then
            echo "qpdf is not installed. Skipping tests that require qpdf."
          else
            echo "qpdf successfully installed"
          fi

      # Step 5: Install qpdf and dependencies on Linux
      - name: Install qpdf (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y qpdf ghostscript

      # Step 6: Install qpdf on Windows using Chocolatey
      - name: Install qpdf (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install qpdf --no-progress

      # Step 7: Install R dependencies
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      # Step 8: Run R CMD check
      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual", "--compact-vignettes=gs+qpdf")'

      # Step 9: Run Code Coverage
      - name: Run code coverage and upload results to Codecov
        run: |
          Rscript -e 'covr::codecov()'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
